# Generated by Django 4.0 on 2022-01-08 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('salary_by_hour', models.FloatField(blank=True, default=0)),
                ('salary_sum', models.FloatField(blank=True, default=0)),
                ('firstday', models.DateField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('boss', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
