# Generated by Django 3.2.11 on 2022-01-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, unique=True, verbose_name='Full name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('salary_by_hour', models.FloatField(blank=True, default=0, verbose_name='Salary by our')),
                ('salary_sum', models.FloatField(blank=True, default=0, verbose_name='Sum salary paid')),
                ('firstday', models.DateField(default=django.utils.timezone.now, verbose_name='First day')),
                ('level', models.IntegerField(blank=True, verbose_name='Level')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('boss', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.employee', verbose_name='Boss')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
