# Generated by Django 4.0 on 2022-01-08 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=100, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(blank=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_by_hour',
            field=models.FloatField(blank=True, default=0, verbose_name='Зарплата за час'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_sum',
            field=models.FloatField(blank=True, default=0, verbose_name='Всего выплачено'),
        ),
    ]
