# Generated by Django 4.0 on 2022-01-08 22:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_fio_alter_employee_firstday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.employee', verbose_name='Начальник'),
        ),
    ]
